#!/usr/bin/env python

import socket
import os
import time

def delay():
    time.sleep(1.1)

def poll(hostname, port):
    s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    s.settimeout(5)
    try:
        s.connect((hostname, port))
        return False
    except: # yes really anything
        return True

def run():
    before, after = os.environ["DB"].split("@")
    hostname, db  = after.split("/")
    port = 5432
    count = 0
    while poll(hostname, port):
        delay()
        count = count + 1
        if count > 10:
            os._exit(1)
    os._exit(0)

if __name__ == '__main__':
    run()
